version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      .env
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - BACKEND_MODE=serve-http
    depends_on: [mongo-db]
    volumes:
      - ./backend:/app/backend
    command: [
      "/usr/local/bin/gunicorn",
      "--bind=0.0.0.0:5000",
      "--access-logfile=-",
      "--access-logformat='%(h)s %(l)s %(u)s %(t)s \"%(r)s\" %(s)s %(b)s \"%(f)s\" \"%(a)s\" %(L)s'",
      "--workers=1",
      "--timeout=600",
      "--limit-request-field_size=65520",
      "--limit-request-line=8188",
      "--reload",
      "app:app"
    ]
    ports:
      - "5000:5000"
  ticker-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on: [mongo-db]
    env_file:
      .env
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - BACKEND_MODE=serve-http
    volumes:
      - ./backend:/app/backend
    command: [
      "python",
      "app_ticker.py"
    ]

  mongo-db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - trader-mongo-data:/data/db
    command: --quiet

volumes:
  trader-mongo-data:
